question_data = [
    {"category": "Animals",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "The K\u0101k\u0101p\u014d is a large, flightless, nocturnal parrot native to which country?",
     "correct_answer": "New Zealand",
     "incorrect_answers": ["South Africa", "Australia", "Madagascar"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "How many legs do butterflies have?",
     "correct_answer": "6", "incorrect_answers": ["2", "4", "0"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A caterpillar has more muscles than humans do.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The Killer Whale is considered a type of dolphin.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What is the collective noun for a group of crows?",
     "correct_answer": "Murder",
     "incorrect_answers": ["Pack", "Gaggle", "Herd"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "What colour is the female blackbird?",
     "correct_answer": "Brown",
     "incorrect_answers": ["Black", "White", "Yellow"]},
    {"category": "Animals", "type": "multiple", "difficulty": "easy",
     "question": "How many teeth does an adult rabbit have?",
     "correct_answer": "28", "incorrect_answers": ["30", "26", "24"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The internet browser Firefox is named after the Red Panda.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
